### ISSUE TITLE
zones vs regios

### ISSUE THREAD

**Issue by premesh** [zjuul/snowplow-gcloud-installer#1]
the setup env file defines the region variable but seems like the zone needs to be passed in some cases ? It failes when running #4

➜  snowplow-gcloud-installer git:(master) ✗ sh 4_spin_up_collector.sh
spinning up instance
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.
Created [https://www.googleapis.com/compute/v1/projects/ranker-stage-snowplow/global/instanceTemplates/sp-coll].
NAME     MACHINE_TYPE  PREEMPTIBLE  CREATION_TIMESTAMP
sp-coll  g1-small                   2019-02-06T17:50:02.128-08:00
Done. Now the firewall rule
Creating firewall...failed.                                                                                                                                                                               
ERROR: (gcloud.compute.firewall-rules.create) Could not fetch resource:
 - The resource 'projects/XXXXX/global/firewalls/collectors-allow-web' already exists

Done. Now creating instance group (managed)
ERROR: (gcloud.beta.compute.instance-groups.managed.create) Could not fetch resource:
 - Invalid value for field 'zone': 'us-west2'. Unknown zone.

Done. Now adding collector
ERROR: (gcloud.compute.instance-groups.managed.set-autoscaling) Could not fetch resource:
 - Invalid value for field 'zone': 'us-west2'. Unknown zone.

Done
➜  snowplow-gcloud-installer git:(master) ✗

**Comment by zjuul** [comment]
Ah.. yes that is confusing. Thanks for bringing this up.

In the config file, there should be a _zone_ name in the GSP_REGION field.
I realised earlier that this was not a good choice, but I forgot to change it.

I'll fix it in the documentation now, and patch it properly later.

for now, please use `export GSP_REGION="us-west2-a"` and it should work.
Later in the script, it strips off the `-a` every time a _region_ is needed, and leaves it like this when a _zone_ is needed.

Does that make sense? Please try, and if it doesn't work, reopen this issue.

**Comment by premesh** [comment]
ok so got me past that issue but fails on the next step
➜  snowplow-gcloud-installer git:(master) ✗ sh 4b_load_balance_collector.sh 
Creating load balancing and DNS
....... health check
Created [https://www.googleapis.com/compute/v1/projects/XXXX/global/healthChecks/sp-collector-healthcheck].
NAME                      PROTOCOL
sp-collector-healthcheck  HTTP
....... create backend-service
Updated [https://www.googleapis.com/compute/v1/projects/XXXXX/zones/us-west2-a/instanceGroups/sp-collector-group].
Created [https://www.googleapis.com/compute/v1/projects/snowplow-ranker-stage/global/backendServices/sp-coll-backend-service].
NAME                     BACKENDS  PROTOCOL
sp-coll-backend-service            HTTP
....... adding backend-service to instance
ERROR: (gcloud.compute.backend-services.add-backend) unrecognized arguments:
  --zone
  us-west2-a
  To search the help text of gcloud commands, run:
  gcloud help -- SEARCH_TERMS
....... url map
Created [https://www.googleapis.com/compute/v1/projects/XXXX/global/urlMaps/sp-coll-url-map].
NAME             DEFAULT_SERVICE
sp-coll-url-map  backendServices/sp-coll-backend-service
Updated [https://www.googleapis.com/compute/v1/projects/XXXX/global/urlMaps/sp-coll-url-map].
4b_load_balance_collector.sh: line 58: syntax error near unexpected token `('
4b_load_balance_collector.sh: line 58: `echo ....... ssl cert (managed by google)'
➜  snowplow-gcloud-installer git:(master) ✗

**Comment by zjuul** [comment]
Fixed now.

In an `echo` command, I used brackets. This is not allowed.
You can edit the file and remove the `(` and `)` on line 58.

**Comment by premesh** [comment]
What about
https://www.googleapis.com/compute/v1/projects/snowplow-ranker-stage/global/backendServices/sp-coll-backend-service
].
NAME BACKENDS PROTOCOL
sp-coll-backend-service HTTP
....... adding backend-service to instance
ERROR: (gcloud.compute.backend-services.add-backend) unrecognized arguments:
--zone
us-west2-a
To search the help text of gcloud commands, run:
gcloud help -- SEARCH_TERMS

**Comment by zjuul** [comment]
```
gcloud compute --project ${GSP_PROJECT_NAME} \
	backend-services add-backend ${GSP_COLLECTOR_INSTANCE_NAME}-backend-service \
	--instance-group ${GSP_COLLECTOR_INSTANCE_GROUP_NAME} \
	--instance-group-zone ${GSP_REGION}
```

Should do it. Fixed.
