### ISSUE TITLE
Errors while executing pubsub script

### ISSUE THREAD

**Issue by danzerzine** [zjuul/snowplow-gcloud-installer#2]
Hi, could you please help me out with PubSub script? 

```
> sh 2_create_pubsub_topics.sh

creating pubsub topics...
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.subscriptions.create) argument --topic: expected one argument
Usage: gcloud pubsub subscriptions create SUBSCRIPTION [SUBSCRIPTION ...] (--topic=TOPIC : --topic-project=TOPIC_PROJECT) [optional flags]
  optional flags may be  --ack-deadline | --help |
                         --message-retention-duration | --push-endpoint |
                         --retain-acked-messages | --topic-project

For detailed information on this command and its flags, run:
  gcloud pubsub subscriptions create --help
ERROR: (gcloud.pubsub.subscriptions.create) argument --topic: expected one argument
Usage: gcloud pubsub subscriptions create SUBSCRIPTION [SUBSCRIPTION ...] (--topic=TOPIC : --topic-project=TOPIC_PROJECT) [optional flags]
  optional flags may be  --ack-deadline | --help |
                         --message-retention-duration | --push-endpoint |
                         --retain-acked-messages | --topic-project

For detailed information on this command and its flags, run:
  gcloud pubsub subscriptions create --help
Done
```

**Comment by zjuul** [comment]
It might be a shell thing. From your output it looks like the function is called and your environment is set, but no argument is passed to the function somehow.

Do you get the same errors when running `./2_create_pubsub_topics.sh` in stead of `sh` ... ?

And can you paste the output of `bash --version` ?

Thanks.

**Comment by danzerzine** [comment]
@zjuul I'm on Mac, maybe that's the reason? 

`bash-5.0$ bash --version
GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin17.7.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.`

**Comment by danzerzine** [comment]
Tried running on Linux with bash with no luck: 

`daniyar@sp-etl:~/snowplow-gcloud-installer$ sh 2_create_pubsub_topics.sh
creating pubsub topics...
Listed 0 items.
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.topics.create) argument TOPIC [TOPIC ...]: Must be specified.
Usage: gcloud pubsub topics create TOPIC [TOPIC ...] [optional flags]
  optional flags may be  --help

For detailed information on this command and its flags, run:
  gcloud pubsub topics create --help
ERROR: (gcloud.pubsub.subscriptions.create) argument --topic: expected one argument
Usage: gcloud pubsub subscriptions create SUBSCRIPTION [SUBSCRIPTION ...] (--topic=TOPIC : --topic-project=TOPIC_PROJECT) [optional flags]
  optional flags may be  --ack-deadline | --help | --push-endpoint |
                         --topic-project

For detailed information on this command and its flags, run:
gcloud pubsub subscriptions create --help
ERROR: (gcloud.pubsub.subscriptions.create) argument --topic: expected one argument
Usage: gcloud pubsub subscriptions create SUBSCRIPTION [SUBSCRIPTION ...] (--topic=TOPIC : --topic-project=TOPIC_PROJECT) [optional flags]
optional flags may be  --ack-deadline | --help | --push-endpoint |
                         --topic-project

For detailed information on this command and its flags, run:
gcloud pubsub subscriptions create --help
Done

daniyar@sp-etl:~/snowplow-gcloud-installer$ bash --version
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. `

**Comment by zjuul** [comment]
I've tested on ubuntu and Mac, so that should work. I'll retest tomorrow and come back to you. 

Also, it's another incentive for me to make the scripts more user-friendly / interactive.

Thanks for the report btw, and thanks for your patience.

**Comment by danzerzine** [comment]
Much appreciated! BTW, really -- thank YOU for putting all this together, really great idea, keep it up :) PS Nice blog, too!

**Comment by zjuul** [comment]
Fixed. The environment wasn't properly loaded in the script. It is now.

--> closed. Thanks!
